version: "3.4"

x-networks: &proxynetwork
  networks:
    - proxy

x-internaldns: &internaldns
  dns: 172.20.10.250

x-nginx: &nginx
  image: nginx:stable-alpine
  working_dir: /application
  volumes:
    - ../..:/application/www:cached
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/fastcgi.conf:/etc/nginx/fastcgi_params

x-redis: &redis
  image: redis:alpine

x-chrome: &chrome
  image: 'selenium/standalone-chrome:3.141.59'
  volumes:
    - '/dev/shm:/dev/shm'
  ports:
    - 4444

x-php: &php
  image: moderntribe/squareone-php:80-2.0
  working_dir: /application
  user: "${SQ1_UID:-1000}:${SQ1_GID:-1000}"
  volumes:
    - ../..:/application/www:cached
    - ./php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/zz-overrides.ini
    - ./php/msmtp.conf:/etc/msmtprc:ro
    - ./wp-cli.yml:/application/wp-cli.yml
    - ./composer:/application/.composer
  external_links:
    - "tribe-mysql:mysql"
    - "tribe-mail:mail"
  environment:
    - COMPOSER_ALLOW_SUPERUSER=1
    - COMPOSER_MEMORY_LIMIT=-1
    - COMPOSER_PROCESS_TIMEOUT=0
    - COMPOSER_HOME=/application/.composer
    - PHP_IDE_CONFIG=serverName=test-site.tribe
    - DOMAIN_CURRENT_SITE=test-site.tribe
    - DB_NAME=tribe_test_site
    - DB_USER=root
    - DB_PASSWORD=password
    - DB_HOST=mysql
    - DB_TABLE_PREFIX=tribe_
    - WP_DEBUG_LOG='php://stderr'

services:

  redis:
    <<: *redis
    <<: *proxynetwork

  php-fpm:
    <<: *php
    <<: *proxynetwork
    <<: *internaldns
    links:
      - redis

  webserver:
    <<: *nginx
    <<: *proxynetwork
    links:
      - php-fpm:php
    environment:
      - VIRTUAL_HOST=test-site.tribe,*.test-site.tribe


  ##################################################
  # Testing Containers
  ##################################################

  redis-tests:
    <<: *redis
    <<: *proxynetwork

  php-tests:
    <<: *php
    <<: *proxynetwork
    <<: *internaldns
    links:
      - redis-tests:redis
      - chrome
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - COMPOSER_MEMORY_LIMIT=-1
      - COMPOSER_PROCESS_TIMEOUT=0
      - COMPOSER_HOME=/application/.composer
      - PAGER=more
      - PHP_IDE_CONFIG=serverName=test-sitetest.tribe
      - DOMAIN_CURRENT_SITE=test-sitetest.tribe
      - DB_NAME=tribe_test_site_acceptance
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_HOST=mysql
      - DB_TABLE_PREFIX=tribe_
      - WP_DEBUG_LOG='php://stderr'
      - TRIBE_GLOMAR=false
      - DISABLE_OBJECT_CACHE=true

  webserver-tests:
    <<: *nginx
    <<: *proxynetwork
    links:
      - php-tests:php
    environment:
      - VIRTUAL_HOST=test-sitetest.tribe,*.test-sitetest.tribe

  chrome:
    <<: *chrome
    <<: *proxynetwork
    <<: *internaldns

networks:
  proxy:
    external: true
    name: global_proxy
